### PR TITLE
UI page.

### PR DESCRIPTION
**Pull request by giosce**
Trying to deploy the draft UI page.

### CODE REVIEW

**Review by k3KAW8Pnf7mkmdSMPHz27 — APPROVED** [review]
Merge from main so that they are up-to-date, but other than that it is good to go

Notes:
1.. I am not sure why the `normalize TOML` workflow is stuck but it works locally (I am using yarn, not npm, shouldn't make too much of a difference)
2. I don't know how mkdocs deals with .HTML files

**Comment by themightychris** [comment]
that might just be because github actions was down all day that day, we just need to get it to re-run

I'm not sure what mkdocs will do about the html file. If it doesn't want to copy it through to output though we can add a mapping under .holo/branches to do copy it in after mkdocs

**Comment by themightychris** [comment]
It looks like the github UI is just totally broken around this job so we can't re-run it online. @giosce try doing this on your branch:

```bash
git commit --amend --no-edit
git push -f
```

This will edit your last commit (on your master branch) and just adjust the timestamp without changing the content/message at all. That's enough to make a new commit ID, and then force push it. That should force github to restart actions

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@giosce is this ready? I am not sure why but I didn't get any notification on the latest push :/

**Review by themightychris — APPROVED** [review]

**Pull request merged**
